variable "engine" {}
variable "instance_class" {}
variable "db_name" {}
variable "db_password" {}
variable "db_username" {}
variable "db_storage" {}
variable "db_sg" {}
variable "db_subnet_group_name" {}
variable "engine_version" {}
variable "db_identifier" {}
variable "multi_az" {}
variable "skip_final_snapshot" {}